services:
  backend:
    build: ./backend
    volumes:
      - ./arctic_data:/app/arctic_db
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000/api
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    depends_on:
      - backend
